### ISSUE TITLE
Issue in windows 10 platform.

### ISSUE THREAD

**Issue by yueeng** [sharpdx/SharpDX#495]
In windows 10 platform when calling GraphicsDevice.New(flags) method will throw a SharpDXException.

```
SharpDX.SharpDXException: HRESULT: [0x887A002D], Module: [SharpDX.DXGI], ApiCode: [DXGI_ERROR_SDK_COMPONENT_MISSING/SdkComponentMissing]

   at SharpDX.Result.CheckError()
   at SharpDX.Direct3D11.Device.CreateDevice(Adapter adapter, DriverType driverType, DeviceCreationFlags flags, FeatureLevel[] featureLevels)
   at SharpDX.Direct3D11.Device..ctor(Adapter adapter, DeviceCreationFlags flags)
   at SharpDX.Toolkit.Graphics.GraphicsDevice..ctor(GraphicsAdapter adapter, DeviceCreationFlags flags, FeatureLevel[] featureLevels)
   at SharpDX.Toolkit.Graphics.GraphicsDevice.New(DriverType type, DeviceCreationFlags flags, FeatureLevel[] featureLevels)
   at SharpDX.Toolkit.Graphics.GraphicsDevice.New(DeviceCreationFlags flags, FeatureLevel[] featureLevels)
   at SwapChainPanelD2D.MainPage.CreateDeviceAndLoadContent()
```

**Comment by xoofx** [comment]
Link updated https://docs.microsoft.com/en-us/windows/uwp/gaming/use-the-directx-runtime-and-visual-studio-graphics-diagnostic-features

**Comment by codecat** [comment]
@xoofx It looks like the instructions on your latest link don't work on the latest builds of Windows 10 (15063 and up), I can't find a "Graphics Tools" on 2 of my computers. On 15063 I only see language support fonts there, while the computer running the on the insider fast ring (16215) actually doesn't show anything in the list at all.

I do have `D3D11SDKLayers.dll` and `d3d11_1sdklayers.dll` in System32 and SysWOW64.
