### ISSUE TITLE
[SharpDX.Direct2D1 v2.6.3] Unable to create a WicRenderTarget on WP 8.1 (WinRT)

### ISSUE THREAD

**Issue by crb9826** [sharpdx/SharpDX#506]
Hi guys,
I'm unable to create a WicRenderTarget in my WP 8.1 WinRT app as it fails with an "NO_HARDWARE_DEVICE" error. It's failing on all of my devices, though it works on the WP 8.1 emulator and also in the Windows 8.1 version of my app. The code is in a portable class library for universal apps that targets Windows 8.1 and WP 8.1 WinRT. I installed SharpDX from NuGet.

I've tested on a Nokia Lumia 930, 925, and 520.

Here's the exception and the stack trace:

```
SharpDX.SharpDXException: HRESULT: [0x8899000B], Module: [SharpDX.Direct2D1], ApiCode: [D2DERR_NO_HARDWARE_DEVICE/NoHardwareDevice], Message: No hardware rendering device is available for this operation.

   at SharpDX.Result.CheckError()
   at SharpDX.Direct2D1.Factory.CreateWicBitmapRenderTarget(Bitmap target, RenderTargetProperties& renderTargetProperties, RenderTarget renderTarget)
   at SharpDX.Direct2D1.WicRenderTarget..ctor(Factory factory, Bitmap wicBitmap, RenderTargetProperties renderTargetProperties)
   at FrameworkElementRendering.Renderer.<RenderToStream>d__7.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at FrameworkElementRendering.Renderer.<Render>d__0.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at myTube.VideoList.<pinIcon_Selected>d__2d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.<ThrowAsync>b__3(Object state)
   at System.Threading.WinRTSynchronizationContext.Invoker.InvokeCore()
```

Here's the code that leads to the exception:

```
public static async Task<MemoryStream> RenderToStream(FrameworkElement el, BitmapType bitmapType)
        {
            await Task.Delay(100);
            var parentBounds = new Rect(0, 0, (el.ActualWidth == 0) ? el.Width : el.ActualWidth, (el.ActualHeight == 0) ? el.Height : el.ActualHeight);

            // pixel format with transparency/alpha channel and RGB values premultiplied by alpha
            var pixelFormat = SharpDX.WIC.PixelFormat.Format32bppPRGBA;

            //pixel format without transparency, but one that works with Cleartype antialiasing
            //var pixelFormat = SharpDX.WIC.PixelFormat.Format32bppBGR;

            var wicFactory = new ImagingFactory();
            var dddFactory = new SharpDX.Direct2D1.Factory();
            var dwFactory = new SharpDX.DirectWrite.Factory();

            var wicBitmap = new SharpDX.WIC.Bitmap(wicFactory, (int)parentBounds.Width, (int)parentBounds.Height, pixelFormat, BitmapCreateCacheOption.CacheOnLoad);

            var renTargProperties = new RenderTargetProperties(
                RenderTargetType.Default, 
                new SharpDX.Direct2D1.PixelFormat(SharpDX.DXGI.Format.R8G8B8A8_UNorm, AlphaMode.Premultiplied),
                //new SharpDX.Direct2D1.PixelFormat(SharpDX.DXGI.Format.Unknown, AlphaMode.Unknown), // use this for non-alpha, cleartype antialiased text
                0, 
                0, 
                RenderTargetUsage.None, 
                FeatureLevel.Level_DEFAULT
                );
            var renTarg = new WicRenderTarget(dddFactory, wicBitmap, renTargProperties)
            {
                TextAntialiasMode = TextAntialiasMode.Grayscale
            };
            // The exception occurs here when creating the WicRenderTarget
```

**Comment by alexsorokoletov** [comment]
According to that source, https://msdn.microsoft.com/en-us/library/windows/desktop/dd371309(v=vs.85).aspx method CreateWicBitmapRenderTarget is not supported on Windows Phone
